sudo: required
services:
  - docker

before_install:
  - docker build -t brianchen/docker-react -f Dockerfile.dev .

script:
  - docker run brianchen/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  #  my region : DockerReact-env.thzvximtzx.us-east-2.elasticbeanstalk.com
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-315024936559"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"